name: Build Module

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Module Zip
        run: |
          mkdir -p module/release
          mkdir -p module/template/webroot
          cp -r webroot/* module/template/webroot/
          cd module/template
          zip -r ../release/enhanced-root-hiding.zip *

      - name: Upload Module Zip
        uses: actions/upload-artifact@v3
        with:
          name: enhanced-root-hiding-module
          path: module/release/enhanced-root-hiding.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            module/release/enhanced-root-hiding.zip
          draft: false
          prerelease: false
          generate_release_notes: true
